// Domain types for Bloom Terminal. These mirror the Core Data Model in the
// README so the backend and frontend speak the same language.

export type EligibilityStatus = "pending" | "eligible";

export type MissionType = "social" | "onchain" | "network" | "terminal";

export interface Mission {
  id: string;
  title: string;
  description: string;
  type: MissionType;
  reward: number;
  /** Completed in the current (mock) session. */
  done: boolean;
  /** An external action (opens X, etc.) vs. an in-app action. */
  external?: boolean;
  /** URL opened when verifying an external task. */
  link?: string;
}

export type AgentStatus =
  | "invited"
  | "connected"
  | "wallet_pending"
  | "active"
  | "eligible";

export interface Agent {
  id: string;
  handle: string;
  status: AgentStatus;
}

export type WorkerClass = "scout" | "analyst" | "momentum" | "sentinel";

export type WorkerStatus =
  | "created"
  | "configured"
  | "ready"
  | "active"
  | "paused";

export interface Worker {
  id: string;
  name: string;
  class: WorkerClass;
  kind: MarketKind;
  asset: string;
  status: WorkerStatus;
  createdAt: number;
  deployedAt: number | null;
  /** Bloom generated by this worker so far (pre-multiplier base). */
  baseEarned: number;
}

export type MarketKind = "STOCKS" | "CRYPTO";

export interface MarketAsset {
  symbol: string;
  name: string;
  kind: MarketKind;
  price: number;
  change: number; // percent
}

export type RewardState =
  | "accumulating"
  | "locked"
  | "eligible"
  | "claimable"
  | "claimed";

export interface ClassInfo {
  id: WorkerClass;
  label: string;
  identity: string;
  purpose: string;
  /** One-line product-facing specification. */
  spec: string;
  focus: string[];
  /** Output modifier applied on top of base production. */
  modifier: number;
}
